language: python
python:
  - '3.9'
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
install:
  - pip install -Ue .[tests]
  - python setup.py install
script: pytest --cov=tc_prometheus tests/ --cov-report term-missing
